### ISSUE TITLE
Compilation broken due to removal of IOpenLoopControl

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/ikart#13]
Hi @randaz81,
the removal of `IOpenLoopControl` breaks compilation of `ikart`. Would be great if this could be fixed.

Best,
Tobias

**Comment by randaz81** [comment]
Thank you! I'm trying to fix all repos as fast as I can.
Can you give it a check now? Thank you!

PS: `devel` branch

**Comment by Tobias-Fischer** [comment]
Works nicely indeed, thanks a lot!
