### ISSUE TITLE
iKart CAD files

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/ikart#4]
Hi,

I'm planning to integrate the iKart to the Gazebo simulator. It'd be great if someone could tell me where to find the CAD files, so I can convert them to `.dae` files needed for the mesh. Ideally, I'm looking for the version including the pole for the Kinect.
@super-ste, do you have an idea?

Thanks a lot,
Tobias

**Comment by super-ste** [comment]
Hi, you can find the iKart model here:

https://svn.robotology.eu/repos/iCubHardware-pub/trunk/mechanics/public/ikart/

open the:
`rc_tlr_013_a_001_ikart.asm.1`

for the iKart and assemble the kinect pole on it:
`rc_iit_013_g_022.asm.1`

if you use CREO (files are saved with the EDUCATIONAL version of 2.0) it has the possibility to export directly to DAE.

Consider check out the whole repo if you need also the commercial components.
Cheers
S.

**Comment by Tobias-Fischer** [comment]
Hi Stefano,

Thanks a lot! That's great :)

Best, Tobi

**Comment by Tobias-Fischer** [comment]
Hi @super-ste,

I just tried to open `rc_tlr_013_a_001_ikart.asm.1`, and it said that some of the files were created with the commercial version of CREO, and are not compatible with the version I am running (Creo Parametric Trial Edition). Could you give me a hint what I am doing wrong? Or, if I can ask you for a favour, could you please export the `dae` file and send it to me :)?

Best, Tobi

**Comment by super-ste** [comment]
Hi @Tobias-Fischer 
may I ask what do you need these files for?
CREO does not export DAE natively but we can probably work out the conversion for you.
Do you need correct masses and inertia or only the graphics? This greatly affect the complexity (hence the filesize) of the model.

**Comment by Tobias-Fischer** [comment]
Hi @super-ste,
I'd like to use these files within Gazebo (see https://github.com/robotology-playground/icub-gazebo). There are already meshes for the iCub available, but not yet for the iKart. I personally would only need the graphics, no need for the correct masses / intertia :).

Thanks! Tobi

**Comment by super-ste** [comment]
Since you ask ... thou shall receive it.

[This is a WeTransfer](http://we.tl/anxESbdMTC)
In the meanwhle we have a week to decide whether to commit this file somewhere meaningful.

Lemme know if it's okay.

**Comment by traversaro** [comment]
@Tobias-Fischer once you have the mesh and the mass of the iKart, you can get the approximate (assuming constant density) inertial parameters as described in : http://gazebosim.org/tutorials?tut=inertia&cat=build_robot (now down, check the cache : http://webcache.googleusercontent.com/search?client=ubuntu&channel=fs&q=cache:http://gazebosim.org/tutorials%3Ftut%3Dinertia%26cat%3Dbuild_robot&ie=utf-8&oe=utf-8&gws_rd=cr&ei=ZREqVoHrOcPYU9WznbgB ).

**Comment by Tobias-Fischer** [comment]
Thanks so much @super-ste! That's great, I'll give it a shot next week. The best place to commit this file would be in the icub-gazebo repository, I think. There are all the other `dae` files for the iCub, so it would make sense to me to have the file for the ikart there as well.
@traversaro: Cool, thank you. The big question is .. how to find the mass? Maybe @super-ste can help (again) :)?

**Comment by super-ste** [comment]
It will take me a little longer.. I hope the masses we have on CAD are accurate. More on this in one week (I'll be OOTO all next week)

**Comment by Tobias-Fischer** [comment]
Just a rough estimate is fine I guess .. as said before, originally I didn't even plan to take the inertia into account at all, but if all it takes is the mass, then I guess we should go for this solution in case someone else is interested as well.

**Comment by traversaro** [comment]
Actually I mentioned the mass because I was expecting it could be obtained by just weighting the physical iKart, but I understand that weight the iKart is probably difficult without a big enough balance. :D 

Anyway, everything depends on how do you plan to simulate the iKart in Gazebo. 
@Tobias-Fischer to you want to open a new issue in this repo or in `icub-gazebo` to discuss how to simulate the iKart in Gazebo (which interfaces to expose, how to simulate mecanum wheels, etc etc)?

**Comment by super-ste** [comment]
From the CAD model
![image](https://cloud.githubusercontent.com/assets/8122012/10697991/f0350890-79ae-11e5-9faa-a8fc4b38ef58.png)

![image](https://cloud.githubusercontent.com/assets/8122012/10698005/0458cc8a-79af-11e5-86fb-420fac07f17f.png)

VOLUME =  3.7211897e+07  MM^3
SURFACE AREA =  6.9842700e+06  MM^2
AVERAGE DENSITY =  2.3132800e-06 KILOGRAM / MM^3
**MASS =  8.6081537e+01 KILOGRAM** 

CENTER OF GRAVITY with respect to _RC_TLR_013_A_001_IKART coordinate frame:
X   Y   Z     8.8538624e+00  1.0638267e+02  1.1821514e+01  MM

INERTIA with respect to _RC_TLR_013_A_001_IKART coordinate frame:  (KILOGRAM \* MM^2)

INERTIA TENSOR:
Ixx Ixy Ixz  4.6205302e+06 -5.6932521e+04  1.2022525e+04
Iyx Iyy Iyz -5.6932521e+04  4.9970526e+06  1.6079353e+05
Izx Izy Izz  1.2022525e+04  1.6079353e+05  4.5354177e+06

INERTIA at CENTER OF GRAVITY with respect to _RC_TLR_013_A_001_IKART coordinate frame:  (KILOGRAM \* MM^2)

INERTIA TENSOR:
Ixx Ixy Ixz  3.6342922e+06  2.4147466e+04  2.1032340e+04
Iyx Iyy Iyz  2.4147466e+04  4.9782748e+06  2.6905003e+05
Izx Izy Izz  2.1032340e+04  2.6905003e+05  3.5544615e+06

PRINCIPAL MOMENTS OF INERTIA:  (KILOGRAM \* MM^2)
I1  I2  I3   3.5032686e+06  3.6357965e+06  5.0279634e+06

ROTATION MATRIX from _RC_TLR_013_A_001_IKART orientation to PRINCIPAL AXES:
      -0.12430        0.99205        0.01975
      -0.17608       -0.04165        0.98349
       0.97650        0.11877        0.17986

ROTATION ANGLES from _RC_TLR_013_A_001_IKART orientation to PRINCIPAL AXES (degrees):
angles about x  y  z -79.636          1.132        -97.142 

RADII OF GYRATION with respect to PRINCIPAL AXES:
R1  R2  R3 2.0173521e+02  2.0551559e+02  2.4168019e+02  MM
